import type { NicheBendSopResult } from "@/lib/types";

export function formatSopAsMarkdown(sop: NicheBendSopResult): string {
  const { content, originalChannel } = sop;

  const lines: string[] = [
    `# ${content.title}`,
    `_${content.subtitle}_`,
    "",
    content.onelinePromise,
    "",
    "## 1. Channel Overview",
    `- Channel: ${content.channelOverview.channel}`,
    `- Niche: ${content.channelOverview.niche}`,
    `- Format: ${content.channelOverview.format}`,
    `- Narration POV: ${content.channelOverview.narrationPov}`,
    `- Avg length: ${content.channelOverview.avgLength}`,
    "- Recurring themes:",
    ...content.channelOverview.recurringThemes.map((item) => `  - ${item}`),
    `- Your-channel note: ${content.channelOverview.yourChannelNote}`,
    "",
    "## 2. Hook Playbook",
    ...content.hookPlaybook.flatMap((hook, i) => [
      `### ${i + 1}. ${hook.template}`,
      `- Used in: ${hook.usedInVideos.join(", ")}`,
      `- Psychology: ${hook.psychology}`,
      `- When to use: ${hook.whenToUse}`,
      "- For your channel:",
      ...hook.forYourChannelExamples.map((example) => `  - ${example}`),
      "",
    ]),
    "## 3. Script Structure Blueprint",
    ...content.scriptStructureBeats.map((beat) => `- **${beat.beat}** (${beat.timing}) — ${beat.function}`),
    "",
    "## 4. Storytelling Frameworks",
    ...content.storytellingFrameworks.flatMap((framework) => [
      `### ${framework.name}`,
      framework.howItWorks,
      `- Used in: ${framework.usedInVideos.join(", ")}`,
      "- Steps:",
      ...framework.steps.map((step, i) => `  ${i + 1}. ${step}`),
      "- Signature phrases:",
      ...framework.signaturePhrases.map((phrase) => `  - ${phrase}`),
      framework.yourChannelMoat ? `- Your-channel moat: ${framework.yourChannelMoat}` : "",
      "",
    ]),
    "## 5. Retention Mechanics",
    "### Rehook Catalog",
    ...content.retentionMechanics.rehookCatalog.map((r) => `- "${r.phrase}" — ${r.whenToUse}`),
    "### Pattern Interrupts",
    ...content.retentionMechanics.patternInterrupts.map((item) => `- ${item}`),
    `### Open Loops\n${content.retentionMechanics.openLoopsRule}`,
    `### Specificity Spikes\n${content.retentionMechanics.specificitySpikesRule}`,
    ...content.retentionMechanics.specificityExamples.map((item) => `- ${item}`),
    "",
    "## 6. Opening & Closing Patterns",
    "### First 30 Seconds",
    ...content.openingClosingPatterns.first30SecondsTemplate.map((line) => `- ${line}`),
    "### Hard Rules",
    ...content.openingClosingPatterns.hardRules.map((rule) => `- ${rule}`),
    `### How Videos End\n${content.openingClosingPatterns.howVideosEnd}`,
    "### Signature Closing Phrases",
    ...content.openingClosingPatterns.signatureClosingPhrases.map((phrase) => `- ${phrase}`),
    "",
    "## 7. Quick Reference Card",
    "**Hook formulas (pick one):**",
    ...content.quickReferenceCard.hookFormulaPicks.map((item) => `- ${item}`),
    `**Structure:** ${content.quickReferenceCard.beatStructureOneLine}`,
    "**Top rehooks:**",
    ...content.quickReferenceCard.topRehooks.map((item) => `- ${item}`),
    "**Do:**",
    ...content.quickReferenceCard.dos.map((item) => `- ${item}`),
    "**Don't:**",
    ...content.quickReferenceCard.donts.map((item) => `- ${item}`),
    "",
    "## Original Channel Analysis",
    `- Channel: ${originalChannel.channelName}`,
    `- Detected niche: ${originalChannel.detectedNiche}`,
    `- Format: ${originalChannel.format}`,
    "",
    "### Top videos",
    ...originalChannel.topVideos.map((video) => `- ${video.title} — ${video.views} views`),
  ];

  return lines.join("\n");
}
