"use client";

import { useState } from "react";
import { Download, Loader2, ArrowRight } from "lucide-react";
import { TikTokIcon } from "@/components/landing/PlatformIcons";

type DemoState = "idle" | "loading_bends" | "show_bends" | "loading_sop" | "show_sop";

type Bend = {
  title: string;
  bullets: string[];
  sopAction?: boolean;
};

const BENDS: Bend[] = [
  {
    title: "Workplace Karma",
    bullets: ["Bosses stealing credit", "HR directors abusing power"],
  },
  {
    title: "Tenant & Landlord Justice",
    bullets: ["Landlords showing up unannounced", "Illegal evictions"],
    sopAction: true,
  },
  {
    title: "HOA Nightmares",
    bullets: ["Neighbors crossing lines", "Petty board presidents"],
  },
];

const TABS = ["Niche Finder", "Bender", "SOP Builder"];

const SOP_MARKDOWN = `# NICHE BEND SOP: Entitlement Karma Stories
**Based on:** Milian (@8BitStoriesof) | **Generated by:** clypo.io

## Section 1: Channel Description
This channel runs animated 2D micro-story Shorts about everyday people facing entitled, manipulative, or unreasonable antagonists — in any setting where those power dynamics play out. Retail, food service, housing, workplaces, transit, online. Every video ends with the antagonist facing real consequences.

The tone is direct and fast. No moralizing. No extended setups. Confrontation, escalation, payoff.

**What makes this distinct vs. Milian:** Milian stays primarily in consumer service (fast food, retail, rideshare). This channel expands across all entitlement arenas — landlords who scam tenants, bosses who steal credit, HOA boards that abuse power, neighbors who cross lines. Wider content universe means more durable channel with no topic exhaustion.

**Content Pillars:**
* Karen/Consumer Confrontations (retail, food service, rideshare)
* Landlord & Housing Power Abuse
* Workplace Entitled Antagonists (managers, HR directors, coworkers)
* Neighbor/HOA Disputes
* Online Scammer Exposure

**Target Viewer:** 18-35, primarily working adults. Watches for vicarious vindication. Has dealt with entitled people and wants to see someone handle it correctly. Rewards specificity.

## Section 2: Information Sources
**Primary Sources:**
* r/EntitledPeople — core Karen/consumer confrontation stories
* r/MaliciousCompliance — stories where someone follows rules to get revenge
* r/ProRevenge — escalated revenge against entitled antagonists
* r/AmItheAsshole — conflict stories with community verdicts
* r/LandlordLegalAdvice and r/TenantRights
* r/antiwork and r/WorkReform
* r/HOA — HOA and neighbor dispute stories

**Topic Discovery Process:**
1. Sort Reddit posts by "Top / Past Month" across those subreddits.
2. Filter for posts with 5K+ upvotes — signals emotional resonance.
3. Look for: clear antagonist, clear conflict, satisfying resolution.
4. Skip stories without a definitive ending — the karma payoff is non-negotiable.

**High-Performance Signals:**
* Specific location + specific behavior in the hook (e.g., "Landlord Who Showed Up Unannounced").
* Sharp reversal — antagonist gets unexpected consequence.
* Clear four-part structure: WHO / WHERE / WHAT THEY DID / RESULT.

## Section 3: Topic Adaptation Framework
**The Pattern:** Apply Milian's hook structure — [Antagonist type] + [specific location or relationship] + [what they did] — across new arenas beyond retail/consumer.

**What Changes vs. What Stays:**
* **Changes:** Location (workplace, housing, neighborhood), antagonist type, consequence type (legal/financial).
* **Stays:** Animation format, micro-story pacing, direct hook, karma resolution, 60-second Shorts structure, 2D character design.

**Adaptation Examples:**
* "Dealing with Karen at McDonald's" → "The Landlord Who Showed Up Unannounced and Regretted It"
* "The Guy Who Ruined Everyone's Vacation" → "The Manager Who Took Credit for the Wrong Project"
* "Karen Gets Karma For Being Annoying" → "The HOA President Who Reported Everyone Until They Got Reported Back"
`;

function AppBarTab({ label, active }: { label: string; active: boolean }) {
  return (
    <span
      className={
        active
          ? "shrink-0 whitespace-nowrap rounded-lg bg-surface px-2.5 py-1 text-xs font-medium text-heading shadow-sm sm:px-3 sm:py-1.5 sm:text-sm"
          : "shrink-0 whitespace-nowrap px-2.5 py-1 text-xs font-medium text-subtle sm:px-3 sm:py-1.5 sm:text-sm"
      }
    >
      {label}
    </span>
  );
}

function SopH2({ children }: { children: string }) {
  return <h2 className="mt-8 mb-3 text-lg font-semibold text-heading first:mt-0">{children}</h2>;
}

function SopBullets({ items }: { items: React.ReactNode[] }) {
  return (
    <ul className="mt-2 flex flex-col gap-1.5">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2 text-sm leading-relaxed text-body">
          <span className="shrink-0 text-subtle">&bull;</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}

function SopOrderedList({ items }: { items: string[] }) {
  return (
    <ol className="mt-2 flex flex-col gap-1.5">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2 text-sm leading-relaxed text-body">
          <span className="shrink-0 font-medium text-subtle">{i + 1}.</span>
          <span>{item}</span>
        </li>
      ))}
    </ol>
  );
}

function SopLabel({ children }: { children: string }) {
  return <p className="mt-4 text-sm font-semibold text-heading">{children}</p>;
}

export function InteractiveDemo() {
  const [state, setState] = useState<DemoState>("idle");

  const handleBendIt = () => {
    setState("loading_bends");
    setTimeout(() => setState("show_bends"), 2000);
  };

  const handleGenerateSop = () => {
    setState("loading_sop");
    setTimeout(() => setState("show_sop"), 2000);
  };

  const handleReset = () => {
    setState("idle");
  };

  const handleDownload = () => {
    const blob = new Blob([SOP_MARKDOWN], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "niche-bend-sop.md";
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto mt-10 relative z-10 px-4 sm:mt-16 sm:px-6 lg:px-8">
      <div className="bg-surface rounded-2xl border border-hairline shadow-2xl overflow-hidden">
        <div className="flex items-center gap-2 border-b border-hairline bg-app px-3 py-2.5 sm:px-4 sm:py-3">
          <div className="hidden shrink-0 items-center gap-2 sm:flex sm:flex-1">
            <span className="h-3 w-3 rounded-full bg-red-400" />
            <span className="h-3 w-3 rounded-full bg-yellow-400" />
            <span className="h-3 w-3 rounded-full bg-green-400" />
          </div>
          <div className="flex flex-1 items-center justify-center gap-1 overflow-x-auto sm:flex-none [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
            {TABS.map((tab) => (
              <AppBarTab key={tab} label={tab} active={tab === "Bender"} />
            ))}
          </div>
          <div className="hidden flex-1 sm:block" />
        </div>

        <div className="p-4 sm:p-8 md:p-12">
          {state === "idle" && (
            <div className="text-center">
              <div className="flex items-center justify-center gap-2">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-pink-500/10 text-pink-600 dark:bg-pink-400/15 dark:text-pink-300 sm:h-8 sm:w-8">
                  <TikTokIcon className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
                </span>
                <h3 className="text-base font-semibold text-heading sm:text-xl md:text-2xl">
                  Generate from TikTok Profile
                </h3>
              </div>

              <div className="mt-6 flex max-w-2xl flex-col gap-2 rounded-xl border border-hairline bg-app p-2 sm:mt-8 sm:mx-auto sm:flex-row sm:items-center">
                <input
                  type="text"
                  readOnly
                  value="https://www.tiktok.com/@8BitStoriesof"
                  className="min-w-0 flex-1 truncate border-none bg-transparent px-3 text-sm text-heading focus:ring-0 sm:px-4 sm:text-base"
                />
                <div className="relative shrink-0 self-end sm:self-auto">
                  <span className="absolute -top-9 right-0 sm:right-auto sm:left-1/2 sm:-translate-x-1/2">
                    <span className="animate-tooltip-bounce relative flex items-center gap-1.5 whitespace-nowrap rounded bg-gray-900 px-2 py-1 text-xs text-white dark:bg-white dark:text-gray-900">
                      <span className="relative flex h-2 w-2 shrink-0">
                        <span className="absolute inline-flex h-full w-full animate-ping rounded-full opacity-75" style={{ backgroundColor: "#00EAF8" }} />
                        <span className="relative inline-flex h-2 w-2 rounded-full" style={{ backgroundColor: "#00EAF8" }} />
                      </span>
                      Start Demo
                      <span className="absolute right-4 top-full h-0 w-0 border-x-4 border-t-4 border-x-transparent border-t-gray-900 dark:border-t-white sm:left-1/2 sm:right-auto sm:-translate-x-1/2" />
                    </span>
                  </span>
                  <button
                    type="button"
                    onClick={handleBendIt}
                    className="w-full rounded-lg bg-btn-primary px-6 py-2.5 font-medium text-white transition-colors hover:bg-btn-primary-hover sm:w-auto"
                  >
                    Bend it
                  </button>
                </div>
              </div>
            </div>
          )}

          {(state === "loading_bends" || state === "loading_sop") && (
            <div className="py-10 flex flex-col items-center gap-4 sm:py-16">
              <Loader2 className="h-8 w-8 text-primary animate-spin" />
              <p className="text-sm font-medium text-subtle">
                {state === "loading_bends"
                  ? "Analyzing viral framework..."
                  : "Generating comprehensive SOP..."}
              </p>
            </div>
          )}

          {state === "show_bends" && (
            <div>
              <h3 className="text-lg font-semibold text-heading">Niche bends for @8BitStoriesof</h3>

              <div className="mt-6 grid grid-cols-1 gap-4 sm:gap-5 md:grid-cols-3">
                {BENDS.map((bend) => (
                  <div
                    key={bend.title}
                    className="border border-hairline rounded-xl p-4 text-left flex flex-col gap-3 sm:p-5"
                  >
                    <span className="text-sm font-semibold text-heading">{bend.title}</span>
                    <ul className="flex flex-col gap-1.5 flex-1">
                      {bend.bullets.map((bullet) => (
                        <li key={bullet} className="flex gap-2 text-sm leading-snug text-body">
                          <span className="shrink-0 text-subtle">&bull;</span>
                          {bullet}
                        </li>
                      ))}
                    </ul>
                    {bend.sopAction && (
                      <button
                        type="button"
                        onClick={handleGenerateSop}
                        className="mt-1 flex items-center gap-1 text-sm font-medium text-primary hover:text-primary-hover"
                      >
                        Generate SOP <ArrowRight className="h-3.5 w-3.5" />
                      </button>
                    )}
                  </div>
                ))}
              </div>

              <button
                type="button"
                onClick={handleReset}
                className="mt-8 text-sm text-subtle hover:text-heading hover:underline"
              >
                Restart demo
              </button>
            </div>
          )}

          {state === "show_sop" && (
            <div className="-m-4 sm:-m-8 md:-m-12">
              <div className="flex flex-wrap items-center justify-between gap-2 px-4 pt-4 pb-4 sm:px-8 sm:pt-8 md:px-12 md:pt-12">
                <h3 className="text-base font-semibold text-heading sm:text-lg">Generated SOP</h3>
                <button
                  type="button"
                  onClick={handleDownload}
                  className="flex items-center gap-1.5 rounded-lg bg-btn-primary hover:bg-btn-primary-hover px-2.5 py-1.5 text-xs font-medium text-white transition-colors sm:px-3 sm:text-sm"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download SOP
                </button>
              </div>

              <div className="max-h-[500px] overflow-y-auto p-4 bg-app text-left sm:p-8 md:p-12">
                <h1 className="text-2xl font-bold text-heading">
                  NICHE BEND SOP: Entitlement Karma Stories
                </h1>
                <p className="mt-2 text-sm text-subtle">
                  <span className="font-semibold text-heading">Based on:</span> Milian (@8BitStoriesof)
                  {" | "}
                  <span className="font-semibold text-heading">Generated by:</span> clypo.io
                </p>

                <SopH2>Section 1: Channel Description</SopH2>
                <p className="text-sm leading-relaxed text-body">
                  This channel runs animated 2D micro-story Shorts about everyday people facing
                  entitled, manipulative, or unreasonable antagonists — in any setting where those
                  power dynamics play out. Retail, food service, housing, workplaces, transit, online.
                  Every video ends with the antagonist facing real consequences.
                </p>
                <p className="mt-3 text-sm leading-relaxed text-body">
                  The tone is direct and fast. No moralizing. No extended setups. Confrontation,
                  escalation, payoff.
                </p>
                <p className="mt-4 text-sm leading-relaxed text-body">
                  <span className="font-semibold text-heading">What makes this distinct vs. Milian:</span>{" "}
                  Milian stays primarily in consumer service (fast food, retail, rideshare). This channel
                  expands across all entitlement arenas — landlords who scam tenants, bosses who steal
                  credit, HOA boards that abuse power, neighbors who cross lines. Wider content universe
                  means more durable channel with no topic exhaustion.
                </p>
                <SopLabel>Content Pillars:</SopLabel>
                <SopBullets
                  items={[
                    "Karen/Consumer Confrontations (retail, food service, rideshare)",
                    "Landlord & Housing Power Abuse",
                    "Workplace Entitled Antagonists (managers, HR directors, coworkers)",
                    "Neighbor/HOA Disputes",
                    "Online Scammer Exposure",
                  ]}
                />
                <p className="mt-4 text-sm leading-relaxed text-body">
                  <span className="font-semibold text-heading">Target Viewer:</span> 18-35, primarily
                  working adults. Watches for vicarious vindication. Has dealt with entitled people and
                  wants to see someone handle it correctly. Rewards specificity.
                </p>

                <SopH2>Section 2: Information Sources</SopH2>
                <SopLabel>Primary Sources:</SopLabel>
                <SopBullets
                  items={[
                    "r/EntitledPeople — core Karen/consumer confrontation stories",
                    "r/MaliciousCompliance — stories where someone follows rules to get revenge",
                    "r/ProRevenge — escalated revenge against entitled antagonists",
                    "r/AmItheAsshole — conflict stories with community verdicts",
                    "r/LandlordLegalAdvice and r/TenantRights",
                    "r/antiwork and r/WorkReform",
                    "r/HOA — HOA and neighbor dispute stories",
                  ]}
                />
                <SopLabel>Topic Discovery Process:</SopLabel>
                <SopOrderedList
                  items={[
                    'Sort Reddit posts by "Top / Past Month" across those subreddits.',
                    "Filter for posts with 5K+ upvotes — signals emotional resonance.",
                    "Look for: clear antagonist, clear conflict, satisfying resolution.",
                    "Skip stories without a definitive ending — the karma payoff is non-negotiable.",
                  ]}
                />
                <SopLabel>High-Performance Signals:</SopLabel>
                <SopBullets
                  items={[
                    'Specific location + specific behavior in the hook (e.g., "Landlord Who Showed Up Unannounced").',
                    "Sharp reversal — antagonist gets unexpected consequence.",
                    "Clear four-part structure: WHO / WHERE / WHAT THEY DID / RESULT.",
                  ]}
                />

                <SopH2>Section 3: Topic Adaptation Framework</SopH2>
                <p className="text-sm leading-relaxed text-body">
                  <span className="font-semibold text-heading">The Pattern:</span> Apply Milian&rsquo;s
                  hook structure — [Antagonist type] + [specific location or relationship] + [what they
                  did] — across new arenas beyond retail/consumer.
                </p>
                <SopLabel>What Changes vs. What Stays:</SopLabel>
                <SopBullets
                  items={[
                    <>
                      <span className="font-semibold text-heading">Changes:</span> Location (workplace,
                      housing, neighborhood), antagonist type, consequence type (legal/financial).
                    </>,
                    <>
                      <span className="font-semibold text-heading">Stays:</span> Animation format,
                      micro-story pacing, direct hook, karma resolution, 60-second Shorts structure, 2D
                      character design.
                    </>,
                  ]}
                />
                <SopLabel>Adaptation Examples:</SopLabel>
                <SopBullets
                  items={[
                    '"Dealing with Karen at McDonald\'s" → "The Landlord Who Showed Up Unannounced and Regretted It"',
                    '"The Guy Who Ruined Everyone\'s Vacation" → "The Manager Who Took Credit for the Wrong Project"',
                    '"Karen Gets Karma For Being Annoying" → "The HOA President Who Reported Everyone Until They Got Reported Back"',
                  ]}
                />
              </div>

              <div className="px-4 py-4 border-t border-hairline sm:px-8 md:px-12">
                <button
                  type="button"
                  onClick={handleReset}
                  className="text-sm text-subtle hover:text-heading hover:underline"
                >
                  Restart demo
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
