// Bundles each MCP App widget (browser TS entry + CSS) into a single
// self-contained HTML document and writes it out as a generated .ts module
// exporting the HTML as a string constant. Run via the `predev`/`prebuild`
// npm lifecycle hooks -- see package.json.
//
// Generated as `export const html = JSON.stringify(...)` rather than a
// backtick template literal so nothing in the bundled JS/CSS (backticks,
// `${`, `</script>`) needs escaping.
import { build } from "esbuild";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIR = path.dirname(fileURLToPath(import.meta.url));
const SHARED_CSS = path.join(DIR, "shared/base.css");
const WIDGETS_DIR = path.join(DIR, "widgets");
const OUT_DIR = path.join(DIR, "generated");

const WIDGETS = [
  "stat-card",
  "list-card",
  "video-grid-card",
  "script-card",
  "image-gallery-card",
  "transcript-card",
  "download-card",
  "creator-profile-card",
];

async function buildWidget(name) {
  const entry = path.join(WIDGETS_DIR, name, "index.ts");
  const cssPath = path.join(WIDGETS_DIR, name, "styles.css");

  const result = await build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2018",
    minify: true,
    logLevel: "silent",
  });
  const js = result.outputFiles[0].text;

  const [sharedCss, widgetCss] = await Promise.all([readFile(SHARED_CSS, "utf-8"), readFile(cssPath, "utf-8")]);

  const html = [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<meta name="color-scheme" content="light dark">',
    `<style>${sharedCss}\n${widgetCss}</style>`,
    "</head>",
    '<body><div id="root"></div>',
    `<script>${js}</script>`,
    "</body></html>",
  ].join("\n");

  const varName = name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  const out = `// Generated by apps/build.mjs -- do not edit directly.\nexport const ${varName}Html = ${JSON.stringify(html)};\n`;
  await writeFile(path.join(OUT_DIR, `${name}.ts`), out, "utf-8");
  console.log(`built ${name} (${(html.length / 1024).toFixed(1)}kb)`);
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  for (const widget of WIDGETS) {
    await buildWidget(widget);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
